backend:
  name: github
  repo: alexling540/gn-test
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: events
    label: Events
    label_singular: Event
    description: Events for the club
    folder: src/pages/events
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{eventName}}"
    summary: "{{eventName}} ({{eventDate}})"
    sortable_fields: ["eventDate"]
    fields:
      - name: eventName
        label: Event name
        widget: string
      - name: eventDate
        label: Date
        widget: datetime
      - name: eventBanner
        label: Banner image
        widget: image
        allow_multiple: false
      - name: eventLocation
        label: Location
        widget: string
      - name: eventDescription
        label: Description
        widget: text
      - name: eventSpeakers
        label: Speakers
        widget: list
        field:
          {
            name: speaker,
            widget: relation,
            collection: people,
            search_fields: ["personName.first", "personName.last"],
            value_field: "{{slug}}",
            display_fields:
              ["{{personName.first}} {{personName.last}} ({{personRole}})"],
          }
      - name: body
        label: Content
        widget: markdown

  - name: people
    label: People
    label_singular: Person
    folder: src/pages/people
    slug: "{{year}}-{{month}}-{{day}}_{{personName.first}}_{{personName.last}}"
    summary: "{{personName.first}} {{personName.last}} ({{personRole}})"
    sortable_fields: ["personName.last", "personRole"]
    view_groups:
      - label: Role
        field: personRole
    create: true
    fields:
      - name: personName
        label: Name
        widget: object
        fields:
          - name: first
            label: First name
            widget: string
          - name: last
            label: Last name
            widget: string
      - name: personPicture
        label: Profile picture
        widget: image
        allow_multiple: false
        required: false
      - name: personRole
        label: Role
        widget: select
        options: ["President", "Vice President", "Officer", "Member", "Guest"]
        default: "Member"
      - name: personIntro
        label: Introduction
        widget: text
      - name: personGitHub
        label: GitHub
        widget: string
        required: false
      - name: personLinkedIn
        label: LinkedIn
        widget: string
        required: false
      - name: personPersonalWebsite,
        label: Personal website
        widget: string
        required: false

  - name: projects
    label: Projects
    label_singular: Project
    folder: src/pages/projects
    create: true
    slug: "{{projectName}}"
    sortable_fields: ["eventName"]
    view_groups:
      - label: Active
        field: projectIsActive
    fields:
      - name: projectName
        label: Project name
        widget: string
      - name: projectIsActive
        label: Active project?
        widget: boolean
      - name: projectBanner
        label: Project banner
        widget: image
        allow_multiple: false
      - name: projectTeam
        label: Team members
        widget: list
        field:
          {
            name: member,
            widget: relation,
            collection: people,
            search_fields: ["personName.first", "personName.last"],
            value_field: "{{slug}}",
            display_fields: ["personName.first", "personName.last"],
          }
      - name: body
        label: Content
        widget: markdown
