backend:
  name: github
  repo: alexling540/gn-test
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: people
    label: People
    label_singular: Person
    folder: src/pages/people
    slug: "{{personName.first}}_{{personName.last}}"
    summary: "{{personName.first}} {{personName.last}} ({{personRole}})"
    create: true
    fields:
      - name: personName
        label: Name
        widget: object
        fields:
          - name: first
            label: First name
            widget: string
          - name: last
            label: Last name
            widget: string
      - name: personPicture
        label: Profile picture
        widget: image
        allow_multiple: false
        required: false
      - name: personRole
        label: Role
        widget: select
        options: ["President", "Vice President", "Officer", "Member", "Guest"]
        default: "Member"
      - name: personIntro
        label: Introduction
        widget: text
      - name: personGitHub
        label: GitHub
        widget: string
        required: false
      - name: personLinkedIn
        label: LinkedIn
        widget: string
        required: false
      - name: personPersonalWebsite,
        label: Personal website
        widget: string
        required: false

  - name: events
    label: Events
    label_singular: Event
    description: Events for the club
    folder: src/pages/events
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{name}}"
    fields:
      - { name: name, label: Event name, widget: string }
      - { name: date, label: Date, widget: datetime }
      - {
          name: banner,
          label: Banner image,
          widget: image,
          allow_multiple: false,
        }
      - { name: location, label: Location, widget: string }
      - { name: description, label: Description, widget: text }
      - {
          name: speakers,
          label: Speakers,
          widget: list,
          field:
            {
              name: speaker,
              widget: relation,
              collection: people,
              search_fields: ["personName.first", "personName.last"],
              value_field: "{{slug}}",
              display_fields: ["personName.first", "personName.last"],
            },
        }

  - name: Projects
    label: Projects
    label_singular: Project
    folder: src/pages/projects
    create: true
    slug: "{{projectName}}"
    fields:
      - { name: name, label: Project name, widget: string }
      - { name: isActive, label: Active project?, widget: boolean }
      - {
          name: banner,
          label: Project banner,
          widget: image,
          allow_multiple: false,
        }
      - { name: body, label: Content, widget: markdown }
