backend:
  name: github
  repo: alexling540/gn-test
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: people
    label: People
    label_singular: Person
    folder: src/pages/people
    slug: "{{firstName}}_{{lastName}}"
    create: true
    fields:
      - { name: firstName, label: First name, widget: string }
      - { name: lastName, label: Last name, widget: string }
      - { name: intro, label: Introduction, widget: text }
      - { name: gitHub, label: GitHub, widget: string, required: false }
      - { name: linkedIn, label: LinkedIn, widget: string, required: false }
      - {
          name: personalWebsite,
          label: Personal website,
          widget: string,
          required: false,
        }

  - name: pages
    label: Pages
    files:
      - file: src/pages/team/team.md
        label: Team
        name: team
        fields:
          - name: president
            label: President
            widget: relation
            collection: people
            search_fields: [firstName, lastName]
            value_field: firstName

          - name: vicePresident
            label: Vice President
            widget: relation
            collection: people
            search_fields: [firstName, lastName]
            value_field: firstName

          - name: officers
            label: Officers
            widget: list
            fields:
              - name: person
                label: Person
                widget: relation
                collection: people
                search_fields: [firstName, lastName]
                value_field: firstName

              - { name: position, label: Position, widget: string }

  - name: events
    label: Events
    label_singular: Event
    folder: src/pages/events
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{name}}"
    fields:
      - { name: name, label: Event name, widget: string }
      - { name: date, label: Date, widget: datetime }
      - {
          name: banner,
          label: Banner image,
          widget: image,
          allow_multiple: false,
        }
      - { name: description, label: Description, widget: text }

  - name: Projects
    label: Projects
    label_singular: Project
    folder: src/pages/projects
    create: true
    slug: "{{projectName}}"
    fields:
      - { name: name, label: Project name, widget: string }
      - {
          name: banner,
          label: Project banner,
          widget: image,
          allow_multiple: false,
        }
